- name: Execute PyInstaller Build
        run: |
          pyinstaller --clean --windowed --name="ADB" adb.py
        shell: bash

      - name: Compress OS-Specific Target
        shell: bash
        run: |
          cd dist
          if [ "$RUNNER_OS" == "macOS" ]; then
            # Compress the .app bundle directory
            zip -r ../ADB-macOS.zip ADB.app
          elif [ "$RUNNER_OS" == "Windows" ]; then
            # Archive the output directory
            7z a ../ADB-Windows.zip ADB
          else
            # Recursively zip the output directory
            zip -r ../ADB-Linux.zip ADB
          fi